// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6gUz9cfw8z8RDxcLf-bl9brbWttx8ulA',
    appId: '1:581097532691:web:0fe2c4fe89a3ca5f64fee6',
    messagingSenderId: '581097532691',
    projectId: 'econo-smart-mobile-app',
    authDomain: 'econo-smart-mobile-app.firebaseapp.com',
    storageBucket: 'econo-smart-mobile-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2gos-Hozn7zwBOM0UWijc3uCTbMCO0AI',
    appId: '1:581097532691:android:1b2203c417ed8a1864fee6',
    messagingSenderId: '581097532691',
    projectId: 'econo-smart-mobile-app',
    storageBucket: 'econo-smart-mobile-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_b_kM6yq59xzw8xN-wT3zx8Qx4ndh7nA',
    appId: '1:581097532691:ios:9d301f6c3a5648f764fee6',
    messagingSenderId: '581097532691',
    projectId: 'econo-smart-mobile-app',
    storageBucket: 'econo-smart-mobile-app.firebasestorage.app',
    iosBundleId: 'com.example.eco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_b_kM6yq59xzw8xN-wT3zx8Qx4ndh7nA',
    appId: '1:581097532691:ios:9d301f6c3a5648f764fee6',
    messagingSenderId: '581097532691',
    projectId: 'econo-smart-mobile-app',
    storageBucket: 'econo-smart-mobile-app.firebasestorage.app',
    iosBundleId: 'com.example.eco',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6gUz9cfw8z8RDxcLf-bl9brbWttx8ulA',
    appId: '1:581097532691:web:dd5012ca3a09203264fee6',
    messagingSenderId: '581097532691',
    projectId: 'econo-smart-mobile-app',
    authDomain: 'econo-smart-mobile-app.firebaseapp.com',
    storageBucket: 'econo-smart-mobile-app.firebasestorage.app',
  );
}
